<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Daily Capacity Report</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #e5e5e5;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            color: #1a1a1a;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #666;
            font-size: 14px;
        }
        .summary-box {
            background-color: #f8f9fa;
            border: 1px solid #e9ecef;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 30px;
        }
        .summary-box h2 {
            margin-top: 0;
            font-size: 18px;
            color: #495057;
        }
        .metrics-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .metrics-table th, .metrics-table td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #dee2e6;
        }
        .metrics-table th {
            background-color: #f1f3f5;
            font-weight: 600;
            color: #495057;
            width: 50%;
        }
        .metrics-table td {
            font-size: 16px;
            font-weight: bold;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #adb5bd;
            border-top: 1px solid #e5e5e5;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Pediatric Dashboard</h1>
        <p>Daily Capacity & Traffic Report</p>
        <p><strong>Date:</strong> {{ $date }}</p>
    </div>

    <div class="summary-box">
        <h2>Daily Aggregates</h2>
        <table class="metrics-table">
            <tr>
                <th>Total Pediatric Processed</th>
                <td>{{ $totalChildren }}</td>
            </tr>
            <tr>
                <th>Total Adults Processed</th>
                <td>{{ $totalAdults }}</td>
            </tr>
            <tr>
                <th>Peak Pediatric Count (Simultaneous)</th>
                <td>{{ $peakChildren }}</td>
            </tr>
            <tr>
                <th>Peak Adult Count (Simultaneous)</th>
                <td>{{ $peakAdults }}</td>
            </tr>
            <tr>
                <th>Total Overcrowding Alerts Triggered</th>
                <td style="color: {{ $alertsCount > 0 ? '#dc3545' : '#28a745' }}">{{ $alertsCount }}</td>
            </tr>
        </table>
    </div>

    <div class="footer">
        Automatically generated by the CV Tracker Engine &bull; {{ config('app.name') }}
    </div>
</body>
</html>
